from __future__ import annotations

import json
from dataclasses import dataclass
from typing import Any, List, Optional


@dataclass
class MockResponse:
    text: str


class MockLLM:
    """
    Deterministic offline LLM stub.
    - generate_content(prompt, stream=False) -> MockResponse
    - If stream=True, returns an iterator of MockResponse chunks (stable).
    """

    def __init__(self, *, mode: str = "baseline_html", seed: int = 0) -> None:
        self.mode = mode
        self.seed = seed

    def generate_content(self, prompt: Any, stream: bool = False) -> Any:
        # Normalize prompt into a string
        if isinstance(prompt, (list, tuple)):
            p = "\n\n".join([str(x) for x in prompt])
        else:
            p = str(prompt)

        if "PLANNER" in p or "planner" in p.lower():
            plan = {
                "web_searches": [],
                "images_to_search_real": [],
                "images_to_generate_creative": [],
                "videos_to_search": [],
                "audio_to_search": [],
                "focus_keywords": [],
                "template_tags": ["dashboard"],
            }
            txt = json.dumps(plan, ensure_ascii=False, indent=2)
            return MockResponse(txt)

        # Check if this is a DSL request (Phase 1)
        is_dsl_request = (
            "OUTPUT FORMAT: JSON ONLY" in p
            or "HMI Architect" in p
            or "Fix the JSON" in p
            or "HMIPanel schema" in p
        )

        if is_dsl_request:
            # Return Valid DSL JSON
            dsl_json = json.dumps(
                {
                    "version": "0.1",
                    "title": "Mock DSL Panel",
                    "description": "Generated by MockLLM for testing",
                    "theme": "dark",
                    "widgets": [
                        {
                            "type": "slider",
                            "id": "mock_slider",
                            "label": "Mock Slider",
                            "min": 0,
                            "max": 100,
                            "step": 1,
                            "value": 50,
                            "binding": {"protocol": "mqtt", "address": "mock/topic"},
                        },
                        {
                            "type": "switch",
                            "id": "mock_switch",
                            "label": "Mock Switch",
                            "on_label": "ON",
                            "off_label": "OFF",
                            "value": False,
                            "binding": {"protocol": "modbus", "address": "40001"},
                        },
                    ],
                    "layout": [
                        {"i": "mock_slider", "x": 0, "y": 0, "w": 6, "h": 2},
                        {"i": "mock_switch", "x": 6, "y": 0, "w": 4, "h": 2},
                    ],
                },
                indent=2,
            )
            return MockResponse(dsl_json)

        # Architect/review path: return a stable HTML (Phase 0)
        html = self._stable_html()

        if stream:
            # return iterable chunks
            chunks = [
                '<!DOCTYPE html>\n<html>\n<head>\n<meta charset="utf-8"/>\n',
                "<title>Mock UI</title>\n</head>\n<body>\n",
                "<h1>Mock UI (offline)</h1>\n<p>health_check OK.</p>\n",
                "</body>\n</html>\n",
            ]
            return (MockResponse(c) for c in chunks)

        return MockResponse(html)

    def _stable_html(self) -> str:
        return (
            "<!DOCTYPE html>\n"
            "<html>\n"
            "<head>\n"
            "  <meta charset=\"utf-8\"/>\n"
            "  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\"/>\n"
            "  <title>Mock UI</title>\n"
            "</head>\n"
            "<body>\n"
            "  <h1>Mock UI (offline)</h1>\n"
            "  <p>health_check OK.</p>\n"
            "</body>\n"
            "</html>\n"
        )
